function [fitresult, gof] = createFit(current, voltage)
%CREATEFIT(CURRENT,VOLTAGE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : current
%      Y Output: voltage
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jul-2018 15:55:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( current, voltage );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'voltage vs. current', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel current
ylabel voltage
grid on


