%%  Gerry + Shomik
%   Galot Track analyze (for simulation)
%   Created May 24, 2018

clear;
load OnlineElevation.mat

m = 23+43; % approx
g = 9.81;
h = smooth(elevation,10);
v = 6.7 - (h-mean(h));
C = 200;
Vi = 16.4;
dx = gradient(d);
dt = dx./v;
t = cumsum(dt);
a = -23.1; b = 388;

Eg = m*g*h;
Ek = 1/2*m*v.^2 .* ones(size(h));
Emotor = 1/2*C*Vi^2 + (mean(Eg)-Eg)+ (mean(Ek)-Ek);
Pmotor = -gradient(Emotor)./dt + 23;
% Vsc = sqrt(2*Emotor/C);
Pmotor = 100 .* (t<69);

eq = @(V,Vpast,t,i) .5*C*V^2 - trapz(t(1:i),(a*[Vpast(1:i-1);V]+b)-Pmotor(1:i)) - 1/2*C*Vi^2;
Vguess = ones(size(t));
Vguess(1) = Vi;
for index = 2:length(t)
    Vguess(index) = fminsearch(@(V) abs(eq(V,Vguess(1:(index-1)),t,index)),15);
end
Vsol = Vguess;
PFC = a*Vsol+b;

figure(1);clf;
subplot(3,1,1);
plot(t,Eg);
ylabel('Eg');
subplot(3,1,2);
plot(t,Ek);
ylabel('Ek');
subplot(3,1,3);
plot(t,Emotor);
ylabel('Emotor');

figure(2);clf;
plot(t,Pmotor,'b-');hold on
plot(t,PFC,'r-');
xlabel('t');ylabel('Power');legend('motor','FC');

figure(3);clf;
plot(t,Vsol);
ylabel('Voltage solution');

fprintf('total energy generated by FC: %.2f\n',trapz(t,PFC))

TtoExport = (0:300)';
VtoExport = interp1(t,Vsol,TtoExport,'linear','extrap');

fprintf('%d, ',TtoExport);
fprintf('\n');
fprintf('%.2f, ',VtoExport);
fprintf('\n');

I = PFC./Vsol;
H2flow = I/1.6021766e-19 / 6.023e23 * 1.01 * 20 + 0.000013;
eff = PFC ./ (H2flow * 119.9e3);

figure(4);clf;
plot(t,eff);

avgEff = trapz(t,PFC) / (trapz(t,H2flow)*119.9e3);
fprintf('average efficiency (theo): %.4f\n',avgEff);

t = TtoExport; V = VtoExport;
save('/Users/Gerry/GIT_REPOS/DEV_H2_DAQ/simulationProfiles/Galot_basic0','t','V')