function [fitresult, gof] = createFit(elapsed, dist, smoothingParam)
%CREATEFIT(ELAPSED,DIST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : elapsed
%      Y Output: dist
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2017 14:29:48

if nargin<3
    smoothingParam = .01;
end

%% Fit: 'Fit'.
[xData, yData] = prepareCurveData( elapsed, dist );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
options = fitoptions('Method','SmoothingSpline',...
                     'SmoothingParam',smoothingParam);

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, options);


